

spring:
  application:
    name: payment-service

resilience4j:
  circuitbreaker:
    instances:
      transactionService:
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
server:
  port: 8083
