# Splunk Integration Configuration
# Add these properties to your application.yml or application.properties

spring:
  application:
    name: auth-service
  
# Splunk Configuration
splunk:
  hec:
    url: http://localhost:8088/services/collector
    token: fintech-hec-token-2024
  index: fintech
  
# Enable async processing for Splunk logging
async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25
  thread-name-prefix: splunk-async-

# Logging configuration for Splunk integration
logging:
  level:
    com.fintech.authservice.service.SplunkLoggingService: INFO
    com.fintech.authservice.service.SecurityEventService: DEBUG
    com.fintech.authservice.service.SessionManagementService: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# HTTP client configuration for Splunk HEC
http:
  client:
    connection-timeout: 5000
    read-timeout: 10000
    max-connections: 20
    
# Security event retention (for database storage)
security:
  events:
    retention-days: 90  # Keep in DB for 90 days, longer retention in Splunk
    cleanup-schedule: "0 2 * * *"  # Run cleanup at 2 AM daily
