version: "3.8"
services:

  postgres:
    image: postgres:15
    container_name: fintech_postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fintech_redis
    ports:
      - "${REDIS_PORT}:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fintech_zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fintech_kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fintech_rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: fintech_jaeger
    ports:
      - "${JAEGER_PORT}:16686"
      - "6831:6831/udp"   # for tracing agent

  splunk:
    image: splunk/splunk:8.2.2
    container_name: fintech_splunk
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
    ports:
      - "${SPLUNK_PORT}:8088"
      - "${SPLUNK_WEB_PORT}:8000"

volumes:
  postgres-data:
