spring.application.name=reporting-service

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Topics
kafka.topics.transaction-completed=transaction-completed
kafka.topics.transaction-failed=transaction-failed
kafka.topics.payment-events=payment-events

# Async Configuration
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20

# Server
server.port=8086

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
