# Performance optimizations for authorization service
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        connection:
          provider_disables_autocommit: true
        query:
          plan_cache_max_size: 2048
        cache:
          use_second_level_cache: false
          use_query_cache: false
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 16
