server:
  port: ${LEDGER_SERVICE_PORT}
  ssl:
    client-auth: need

spring:
  application:
    name: ledger-service

  kafka:
    consumer:
      group-id: ledger-service-group
      client-id: ledger-service-consumer

    producer:
      client-id: ledger-service-producer


  # Database Configuration using ShardingSphere-Proxy
  datasource:
    url: ${AUTH_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  data:
    redis:
      database: 3
