server:
  port: ${NOTIFICATION_SERVICE_PORT}

spring:
  application:
    name: notification-service

  # Database Configuration using ShardingSphere-Proxy
  datasource:
    url: ${AUTH_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  data:
    redis:
      database: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-dev-email@gmail.com
    password: your-dev-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true