server:
  port: ${REPORTING_SERVICE_PORT}

spring:
  application:
    name: reporting-service
  datasource:
  config:
    url: ${AUTH_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      database: 6
