server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: auth-service
  datasource:
    main:
      url: ${MAIN_DB_URL}
    shard1:
      url: ${SHARD1_DB_URL}
    shard2:
      url: ${SHARD2_DB_URL}
    shard3:
      url: ${SHARD3_DB_URL}
  data:
    redis:
      database: 0 # Redis DB for session management

jwt:
  keystore-path: ${JWT_KEYSTORE_PATH}
  keystore-password: ${JWT_KEYSTORE_PASSWORD}
  key-alias: ${JWT_KEY_ALIAS}
  access-token-expiration: 60000
  refresh-token-expiration: 600000

resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
  retry:
    instances:
      auth-service:
        max-attempts: 3
        wait-duration: 1s
  timelimiter:
    instances:
      auth-service:
        timeout-duration: 5s
