server:
  port: ${AUTHORIZATION_SERVICE_PORT}

spring:
  application:
    name: authorization-service
  datasource:
    url: ${AUTH_DB_URL}
  data:
    redis:
      database: 1 # Redis DB for authorization caching

resilience4j:
  circuitbreaker:
    instances:
      authorization-check:
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
      redis-cache:
        sliding-window-size: 50
        minimum-number-of-calls: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
  retry:
    instances:
      authorization-retry:
        max-attempts: 3
        wait-duration: 500ms
  timelimiter:
    instances:
      authorization-service:
        timeout-duration: 3s
