server:
  port: ${GATEWAY_SERVICE_PORT}
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: ${SSL_KEYSTORE_TYPE}
    key-alias: ${SSL_KEY_ALIAS}
jwt:
  public-cert-path: ${JWT_PUBLIC_CERT_PATH}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:${AUTH_SERVICE_PORT}
          predicates:
            - Path=/api/auth/**
        - id: authorization-service
          uri: http://authorization-service:${AUTHORIZATION_SERVICE_PORT}
          predicates:
            - Path=/api/authorization/**
        - id: user-service
          uri: http://user-service:${USER_SERVICE_PORT}
          predicates:
            - Path=/api/user/**
        - id: payment-service
          uri: http://payment-service:${PAYMENT_SERVICE_PORT}
          predicates:
            - Path=/api/payment/**
        - id: transaction-service
          uri: http://transaction-service:${TRANSACTION_SERVICE_PORT}
          predicates:
            - Path=/api/transaction/**
        - id: notification-service
          uri: http://notification-service:${NOTIFICATION_SERVICE_PORT}
          predicates:
            - Path=/api/notification/**
        - id: reporting-service
          uri: http://reporting-service:${REPORTING_SERVICE_PORT}
          predicates:
            - Path=/api/reporting/**
        - id: scheduler-service
          uri: http://scheduler-service:${SCHEDULER_SERVICE_PORT}
          predicates:
            - Path=/api/scheduler/**
        - id: retry-service
          uri: http://retry-service:${RETRY_SERVICE_PORT}
          predicates:
            - Path=/api/retry/**
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,GATEWAY_TIMEOUT
            methods: GET,POST
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false

resilience4j:
  timelimiter:
    instances:
      gateway-service:
        timeout-duration: 5s
