server:
  port: ${NOTIFICATION_SERVICE_PORT}

spring:
  application:
    name: notification-service
  datasource:
    main:
      url: ${MAIN_DB_URL}
    shard1:
      url: ${SHARD1_DB_URL}
    shard2:
      url: ${SHARD2_DB_URL}
    shard3:
      url: ${SHARD3_DB_URL}
  data:
    redis:
      database: 5 # Redis DB for notification caching
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

resilience4j:
  circuitbreaker:
    instances:
      email-sender:
        sliding-window-size: 50
        minimum-number-of-calls: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 15s
  retry:
    instances:
      notification-retry:
        max-attempts: 3
        wait-duration: 1s
  timelimiter:
    instances:
      notification-service:
        timeout-duration: 10s
