server:
  port: ${PAYMENT_SERVICE_PORT}

spring:
  application:
    name: payment-service
  datasource:
    main:
      url: ${MAIN_DB_URL}
    shard1:
      url: ${SHARD1_DB_URL}
    shard2:
      url: ${SHARD2_DB_URL}
    shard3:
      url: ${SHARD3_DB_URL}
  data:
    redis:
      database: 4 # Redis DB for payment caching

resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
  retry:
    instances:
      paymentProcessing:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    instances:
      paymentApi:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
