server:
  port: ${REPORTING_SERVICE_PORT}

spring:
  application:
    name: reporting-service
  datasource:
    main:
      url: ${MAIN_DB_URL}
    shard1:
      url: ${SHARD1_DB_URL}
    shard2:
      url: ${SHARD2_DB_URL}
    shard3:
      url: ${SHARD3_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate # This service should be read-only
  data:
    redis:
      database: 6 # Redis DB for report caching

resilience4j:
  circuitbreaker:
    instances:
      report-generator:
        sliding-window-size: 20
        minimum-number-of-calls: 5
        failure-rate-threshold: 40
        wait-duration-in-open-state: 60s
  retry:
    instances:
      reporting-retry:
        max-attempts: 2
        wait-duration: 2s
  timelimiter:
    instances:
      reporting-service:
        timeout-duration: 30s
