spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/userdb
  redis:
    cache-key-prefix: user-cache

server:
  port: 8089

management:
  tracing:
    enabled: true
