spring:
  cloud:
    config:
      fail-fast: true
  
  # Common configuration imports
  config:
    import: 
      - C:/spring-boot/fintech-project/services/config-repo/dev/common-logging-config-dev.yml
      - C:/spring-boot/fintech-project/services/config-repo/dev/common-observability-config-dev.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  
  # Common infrastructure configuration for local development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceName: fintech-scheduler-dev
      org.quartz.threadPool.threadCount: 10
