server:
  port: 8085

jwt:
  public-cert-path: C:/spring-boot/fintech-project/certs/jwt-public.crt

spring:
  application:
    name: authorization-service
  
  # Database Configuration - Authorization service uses dedicated auth database
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech_main
    username: fintech_user
    password: fintech_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 10000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      max-lifetime: 1800000
      keepalive-time: 600000

  data:
    redis:
      database: 0
  # Kafka Configuration for internal service communications
  kafka:
    consumer:
      group-id: authorization-service-group
      client-id: authorization-service-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.fintech.userservice.dto,com.fintech.authservice.dto.response
        enable.auto.commit: false
        auto.offset.reset: earliest
        max.poll.records: 10

