server:
  port: 8080

jwt:
  public-cert-path: C:/spring-boot/fintech-project/certs/jwt-public.crt
spring:
  application:
    name: gateway-service-dev
  cloud:
    gateway:
      preserveHostHeader: true
      # Routes point to other services running on localhost at their respective ports
      routes:
        - id: auth-service
          uri: https://localhost:8081
          predicates:
            - Path=/api/auth/**
#        - id: authorization-service
#          uri: https://localhost:8085
#          predicates:
#            - Path=/api/authorization/**
#          filters:
#            - name: JwtAuthGatewayFilter
        - id: user-service
          uri: https://localhost:8089
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: payment-service
          uri: https://localhost:8084
          predicates:
            - Path=/api/payment/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: transaction-service
          uri: https://localhost:8086
          predicates:
            - Path=/api/transaction/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: notification-service
          uri: https://localhost:8083
          predicates:
            - Path=/api/notification/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: reporting-service
          uri: https://localhost:8088
          predicates:
            - Path=/api/reporting/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: scheduler-service
          uri: https://localhost:8090
          predicates:
            - Path=/api/scheduler/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: retry-service
          uri: https://localhost:8091
          predicates:
            - Path=/api/retry/**
          filters:
            - name: JwtAuthGatewayFilter
gateway:
  authz:
    base-url: https://localhost:8085
    introspect-path: /authz/introspect
    timeout-ms: 3000